# Generated by Django 2.2.2 on 2019-06-16 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='ends_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='starts_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
