# Generated by Django 2.2.2 on 2019-06-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, default='항목을 입력하세요', max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.Poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='ends_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='starts_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
