# Generated by Django 2.2.2 on 2019-06-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190618_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='ends_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='starts_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
