# Generated by Django 2.2.2 on 2019-06-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190616_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='starts_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
