# Generated by Django 2.2.2 on 2019-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190618_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
