# Generated by Django 2.2.2 on 2019-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190618_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
