# Generated by Django 2.2.2 on 2019-06-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190618_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
