# Generated by Django 2.2.2 on 2019-06-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190618_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='poll',
            new_name='poll_id',
        ),
    ]
